name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
description: ${project.description}
author: NerdsWBNerds
url: ${project.url}
api-version: 1.13
commands:
   tempban:
      description: Temporarily ban a player
      usage: /tempban <player> <amount> <unit> [reason]
      aliases: [tban,tb]
