name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
description: ${project.description}
author: NerdsWBNerds
url: ${project.url}
api-version: 1.13
commands:
   tempban:
      description: Used to temporarily ban online players.
      usage: /tempban <player> <amount> <unit>
      aliases: [tban,tb]
